services:
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=payments
      - POSTGRES_PASSWORD=payments
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_INITDB_ARGS=--data-checksums
    deploy:
      resources:
        limits:
          memory: 120M
          cpus: '0.40'
    ports:
      - 5432:5432
    networks:
      - rinha
  nginx:
    image: nginx:1.25-alpine
    hostname: nginx
    depends_on:
      - api01
      - api02
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          memory: 25M
          cpus: '0.1'
    volumes:
      - .config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha
  cache:
    image: redis:7.2-alpine
    command:
      [
        'redis-server',
        '--appendonly',
        'no',
        '--appendfsync',
        'no',
        '--save',
        '',
        '--maxclients',
        '20000',
        '--maxmemory',
        '35mb',
      ]
    hostname: cache
    deploy:
      resources:
        limits:
          memory: 30M
          cpus: '0.2'
    ports:
      - 6379:6379
    networks:
      - rinha
  api01: &api
    hostname: api01
    build:
      context: .
    deploy:
      resources:
        limits:
          memory: 85M
          cpus: '0.40'
    environment:
      - APP_PORT=8080
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - PAYMENTS_DEFAULT_GATEWAY_URL=http://payment-processor-default:8080/payments
      - PAYMENTS_FALLBACK_GATEWAY_URL=http://payment-processor-fallback:8080/payments
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=payments
      - POSTGRES_USER=payments
      - POSTGRES_PASSWORD=payments
    depends_on:
      - cache
      - postgres
    networks:
      - rinha
      - payment-processor
  api02:
    <<: *api
    hostname: api02
networks:
  rinha:
    driver: bridge
  payment-processor:
    external: true
