services:
  nginx:
    image: nginx:latest
    hostname: nginx
    ports:
      - 9999:9999
    volumes:
      - .config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '30MB'
  cache:
    image: redis:latest
    hostname: cache
    ports:
      - 6379:6379
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '70MB'
  api01: &api
    hostname: api01
    build:
      context: .
    environment:
      - APP_PORT=8080
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - PAYMENTS_DEFAULT_GATEWAY_URL=http://payment-processor-default:8080/payments
      - PAYMENTS_FALLBACK_GATEWAY_URL=http://payment-processor-fallback:8080/payments
    depends_on:
      - cache
    networks:
      - rinha
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '125MB'
  api02:
    <<: *api
    hostname: api02
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '125MB'
networks:
  rinha:
    driver: bridge
  payment-processor:
    external: true
