services:
  payment-gateway-hc:
    build:
      context: ./payment-gateway-hc
      dockerfile: Dockerfile
    hostname: payment-gateway-hc
    deploy:
      resources:
        limits:
          memory: 30M
          cpus: "0.05"
    environment:
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - PAYMENTS_DEFAULT_GATEWAY_URL=http://payment-processor-default:8080/payments
      - PAYMENTS_FALLBACK_GATEWAY_URL=http://payment-processor-fallback:8080/payments
    networks:
      - rinha
      - payment-processor
  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_DB=payments
      - POSTGRES_USER=payments
      - POSTGRES_PASSWORD=payments
      - POSTGRES_INITDB_ARGS=--data-checksums
      - PGDATA=/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          memory: 70M
          cpus: "0.4"
    ports:
      - 5432:5432
    networks:
      - rinha
  nginx:
    image: nginx:latest
    hostname: nginx
    depends_on:
      - api01
      - api02
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          memory: 20M
          cpus: "0.05"
    volumes:
      - .config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - rinha
  cache:
    image: redis:latest
    hostname: cache
    deploy:
      resources:
        limits:
          memory: 30M
          cpus: "0.1"
    ports:
      - 6379:6379
    networks:
      - rinha
  api01: &api
    hostname: api01
    build:
      context: ./payment-processor
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          memory: 100M
          cpus: "0.45"
    environment:
      - APP_PORT=8080
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - PAYMENTS_DEFAULT_GATEWAY_URL=http://payment-processor-default:8080/payments
      - PAYMENTS_FALLBACK_GATEWAY_URL=http://payment-processor-fallback:8080/payments
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=payments
      - POSTGRES_USER=payments
      - POSTGRES_PASSWORD=payments
    depends_on:
      - cache
      - postgres
    networks:
      - rinha
      - payment-processor
  api02:
    <<: *api
    hostname: api02
networks:
  rinha:
    driver: bridge
  payment-processor:
    external: true